# docker-compose.yml

version: '3.9'
services:
  frontend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/usr/app/src:ro
    expose:
      - 3000
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_NAME=MRX-APP-DEV
    # env_file:
    #   - ./.env
