# Dockerfile

# Pull the base image
FROM node:alpine

# set working directory
# RUN mkdir /usr/app

# Set the working directory
WORKDIR /usr/app

# Copy app dependencies to container
COPY ./package*.json ./

# Add `/usr/app/node_modules/.bin` to $PATH
# ENV PATH /usr/app/node_modules/.bin:$PATH

# Install dependencies
RUN npm install

# Copy app dependencies to container
COPY ./ ./

# Expose port to container
EXPOSE 3000

# Deploy app for local development
CMD ["npm", "start"]